### ISSUE TITLE
Leaves disappearing off of trees.

### ISSUE THREAD

**Issue by RandomGuy000** [Modding-Legacy/Aether-Legacy-Rift#21]
When I install Aether, trees in the overworld start loosing leaves. I already tried using different versions of Fabric Loader and Fabric API, but it all came down to Aether being the cause.

**Comment by CDAGaming** [comment]
@RandomGuy000 Fixed in https://github.com/Modding-Legacy/Aether-Legacy-Rift/commit/fbfe117775f39ea767dec5ed65a529b77713fac7

Stay Tuned to the Next Release!
