### ISSUE TITLE
Rift 1.13.2 Launcher crash

### ISSUE THREAD

**Issue by Schmarbier** [Modding-Legacy/Aether-Legacy-Rift#23]
Start Launcher, Crash
Log: [latest.log](https://github.com/Modding-Legacy/Aether-Legacy-Rift/files/2948605/latest.log)

**Comment by CDAGaming** [comment]
@Schmarbier Last I checked, fi.dy.masa.malilib.interfaces.IInitializationHandler (The class it's crashing on) is NOT apart of Aether Legacy...
